# Generated by Django 6.0.5 on 2026-05-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='icone',
            field=models.CharField(blank=True, default='🏷️', max_length=10, null=True),
        ),
    ]
