# Generated by Django 6.0.5 on 2026-05-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_categorie_user_remove_fournisseur_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
