# Generated by Django 6.0.5 on 2026-06-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_produit_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='nom_complet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
